version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SECRET_KEY=SECRET_KEY_JWT_TOKEN
      - MYSQL_USER=root
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=Aec19cs047
      - MYSQL_DATABASE=test
      - MYSQL_PORT=3306  # Use the default MySQL port inside the container
    depends_on:
      mysql:
        condition: service_healthy
    
  
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Aec19cs047
      MYSQL_DATABASE: test
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
